### ISSUE TITLE
Do you have Guna. Charts. WinForms?

### ISSUE THREAD

**Issue by wkfy** [CabboLeak/GunaFrameWorkCracked#4]
Do you have Guna. Charts. WinForms?

**Comment by CabboLeak** [comment]
I will crack the latest version today or tomorrow, thank you.
Check the Guna Charts Repository in the next days thanks.
Cabbo.

**Comment by wkfy** [comment]
Great. Thank you very much！

**Comment by CabboLeak** [comment]
Hello.
Please check here: https://github.com/CabboLeak/GunaChartsCracked
I have updated the Library from V1.0.4 to V1.0.8 (latest as 20/04/2023).
Hope you enjoy.
Cabbo.
